server:
  port: 8082
spring:
  application:
    name: user-management
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2db
    username: admin
    password: admin
  jpa:
    show-sql: true
  jackson:
    serialization.write-dates-as-timestamps: false