INSERT INTO ROLE (STR_ROLE)VALUES('Gerente');
INSERT INTO ROLE (STR_ROLE)VALUES('Supervisor');
INSERT INTO ROLE (STR_ROLE)VALUES('Administrativo');

INSERT INTO PROFILE (STR_PROFILE)VALUES('Administrador');
INSERT INTO PROFILE (STR_PROFILE)VALUES('Comum');


