DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS PROFILE;

CREATE TABLE USER(
    NUM_ID INTEGER NOT NULL PRIMARY KEY,
    STR_NAME VARCHAR(255) NOT NULL,
    STR_CPF VARCHAR(255) NOT NULL,
    STR_GENDER VARCHAR(255) NOT NULL,
    DAT_BIRTH DATE NOT NULL,
    STATUS INT NOT NULL
);

CREATE TABLE ROLE(
    NUM_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STR_ROLE VARCHAR(255)
);

CREATE TABLE PROFILE(
    NUM_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STR_PROFILE VARCHAR(100) NOT NULL
);

