DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS PROFILE;

CREATE TABLE USER(
    STR_NAME VARCHAR(255) NOT NULL,
    STR_CPF VARCHAR(255) NOT NULL,
    STR_GENDER VARCHAR(255) NOT NULL,
    DAT_BIRTH DATE NOT NULL,
    STATUS INT NOT NULL,
    NUM_ROLE_ID INTEGER NOT NULL,
    NUM_PROFILE_ID INTEGER NOT NULL
);

ALTER TABLE USER ADD CONSTRAINT PK_USER PRIMARY KEY (
    STR_NAME, STR_CPF
);

CREATE TABLE ROLE(
    NUM_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STR_ROLE VARCHAR(255)
);

CREATE TABLE PROFILE(
    NUM_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STR_PROFILE VARCHAR(100) NOT NULL
);

ALTER TABLE USER
    ADD FOREIGN KEY (NUM_ROLE_ID)
    REFERENCES ROLE(NUM_ID);

ALTER TABLE USER
    ADD FOREIGN KEY (NUM_PROFILE_ID)
    REFERENCES PROFILE(NUM_ID);

